sonar.projectKey=wps-yundoc-admin-console
sonar.projectName=WPS Yundoc Admin Console
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=dist/**,coverage/**,node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.eslint.reportPaths=eslint-report.json
sonar.sourceEncoding=UTF-8
